---
title: "Wage Comparison Between Ethnic Groups in the Technology Sector"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r setup, include=FALSE, cashe = TRUE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(rmarkdown)
library(knitr)
library(stargazer)
library(ggplot2)
library(vctrs)
library(plyr)
library(dplyr)
library(plotly)

mywd <- "C:/Users/Quinc/OneDrive/Murray State/Spring 2021/CIS 361"
setwd(mywd)


myfile <- "survey_results_public.csv"

Alldata <- read.csv(file = myfile, header = TRUE, sep = ",")

SmallData <- dplyr::select(Alldata, Respondent, Employment, Country, Ethnicity, DevType
                    , YearsCode, CompTotal, WorkWeekHrs, Age, Gender)
SmallData <-na.omit(SmallData)

FromUSA <- SmallData %>% filter(Country == 'United States', Employment == 'Employed full-time')

#Remove rows with null values
FromUSA <- na.omit(FromUSA)

#Narrowing the scope of DevTypes
FromUSA[] <- FromUSA %>% 
  group_by(DevType) %>%
  arrange(DevType)
i <- 0
while (i <= 533){
  FromUSA$DevType[i] <- "Academic researcher"
  i = i + 1
}
while (i <= 1490){
  FromUSA$DevType[i] <- "Data or business analyst"
  i = i + 1
}
while (i <= 2000){
  FromUSA$DevType[i] <- "Data scientist or machine learning specialist"
  i = i + 1
}
while (i <= 2943){
  FromUSA$DevType[i] <- "Database administrator"
  i = i + 1
}
while (i <= 3620){
  FromUSA$DevType[i] <- "Designer"
  i = i + 1
}
while (i <= 12083 ){
  FromUSA$DevType[i] <- "Developer"
  i = i + 1
} 
while (i <= 12200 ){
  FromUSA$DevType[i] <- "DevOps specialist"
  i = i + 1
} 
while (i <= 12221 ){
  FromUSA$DevType[i] <- "Educator"
  i = i + 1
}
while (i <= 12433  ){
  FromUSA$DevType[i] <- "Engineer"
  i = i + 1
}
while (i <= 12465 ){
  FromUSA$DevType[i] <- "Product manager"
  i = i + 1
}
while (i <= 12488  ){
  FromUSA$DevType[i] <- "Scientist"
  i = i + 1
}
while (i <= 12537 ){
  FromUSA$DevType[i] <- "Senior executive/VP"
  i = i + 1
}
while (i <= 12541 ){
  FromUSA$DevType[i] <- "Student"
  i = i + 1
} 

FromUSA$YearsCode[grepl("More than 50 years",FromUSA$YearsCode)]<-'55'
FromUSA$YearsCode[grepl("Less than 1 year",FromUSA$YearsCode)]<-'1'
FromUSA$YearsCode <- as.numeric(FromUSA$YearsCode)

Biracial <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'Biracial')

BlackorofAfricandescent <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'Black or of African descent')


EastAsian <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'East Asian')


Hispanic <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'Hispanic or Latino/Latina')



MiddleEastern <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'Middle Eastern')

Native <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'Native American, Pacific Islander, or Indigenous Australian')


SouthAsian <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'South Asian') 

WhiteorEuropeandescent <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'White or of European descent')

Multiracial <- FromUSA %>%
  select(DevType, Ethnicity, WorkWeekHrs, CompTotal, Age, YearsCode) %>%
  filter(Ethnicity == 'Multiracial')
```

Multiracial
=======================================================================

```{r Multiracial}
options(scipen=999)


a <-ggplot(Multiracial, aes(x=DevType, y=CompTotal, fill = DevType))  +
        geom_col() + labs(title="Multiracial",
       y="Wage", x="Developer Type", caption="Multiracial") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
  ggplotly(a)
```

White or European descent
=======================================================================

```{r WhiteorEuropeandescent}
j <-ggplot(WhiteorEuropeandescent, aes(x=DevType, y=CompTotal, fill = DevType)) +
        geom_col() + labs(title="White or European descent",
       y="Wage", x="Developer Type", caption="White or European descent") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
ggplotly(j)
```

South Asian
=======================================================================

```{r SouthAsian}
h <-ggplot(SouthAsian, aes(x=DevType, y=CompTotal, fill = DevType))  +
        geom_col() + labs(title="South Asian",
       y="Wage", x="Developer Type", caption="South Asian") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
 ggplotly(h)

```

Native American, Pacific Islander, or Indigenous Australian
=======================================================================

```{r Native}
    g <-ggplot(Native, aes(x=DevType, y=CompTotal, fill = DevType))  +
        geom_col() + labs(title="Native American, Pacific Islander, or Indigenous Australian",
       y="Wage", x="Developer Type", caption="Native American, Pacific Islander, or Indigenous Australian") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
ggplotly(g)
```

Middle Eastern
=======================================================================

```{r MiddleEastern}
f <-ggplot(MiddleEastern, aes(x=DevType, y=CompTotal, fill = DevType))  +
        geom_col() + labs(title="Middle Eastern",
       y="Wage", x="Developer Type", caption="Middle Eastern") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
ggplotly(f)
```

Hispanic or Latino/Latina
=======================================================================

```{r Hispanic}
e <-ggplot(Hispanic, aes(x=DevType, y=CompTotal, fill = DevType))  +
        geom_col() + labs(title="Hispanic or Latino/Latina",
       y="Wage", x="Developer Type", caption="Hispanic or Latino/Latina") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
 ggplotly(e)
```

East Asian
=======================================================================

```{r EastAsian}
d <-ggplot(EastAsian, aes(x=DevType, y=CompTotal, fill = DevType))  +
        geom_col() + labs(title="East Asian",
       y="Wage", x="Developer Type", caption="East Asian") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
 ggplotly(d)

```

Black or of African descent
=======================================================================

```{r BlackorofAfricandescent}
c <-ggplot(BlackorofAfricandescent, aes(x=DevType, y=CompTotal, fill = DevType))  +
        geom_col() + labs(title="Black or of African descent",
       y="Wage", x="Developer Type", caption="Black or of African descent") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
 ggplotly(c)
```

Biracial
=======================================================================

```{r Biracial}
b <-ggplot(Biracial, aes(x=DevType, y=CompTotal, fill = DevType))  +
        geom_col() + labs(title="Biracial",
       y="Wage", x="Developer Type", caption="Biracial") +
  scale_x_discrete(labels = c('A','B','C','D','E','F','G','H','I','J','K','L', 'M','N'))
 ggplotly(b)
```

